export const cartConfig = {
  items: [
    { id: 1, type: "food", name: "Chocolate Bar", price: 0.85 },
    { id: 2, type: "electronics", name: "Music Player", price: 49.99 },
    { id: 3, type: "cosmetics", name: "Perfume", price: 47.50 },
    { id: 4, type: "medical", name: "Packet of Headache Pills", price: 9.75 },
    { id: 5, type: "music", name: "Music CD", price: 14.99 },
    { id: 6, type: "book", name: "Fahrenheit 451", price: 12.49 },
    { id: 7, type: "food", name: "Chocolate bar", price: 0.85 },
    { id: 8, type: "book", name: "1984 by George Orwell", price: 15.0 },
    { id: 9, type: "medical", name: "Antibiotic Cream", price: 7.25 },
    { id: 10, type: "cosmetics", name: "Lipstick", price: 27.99 },
    { id: 11, type: "electronics", name: "Wireless Mouse", price: 18.99 },
    { id: 12, type: "food", name: "Bottle of Orange Juice", price: 1.75 },
    { id: 13, type: "book", name: "The Hobbit", price: 13.99 },
    { id: 14, type: "medical", name: "Pack of Bandages", price: 3.49 },
    { id: 15, type: "clothing", name: "Baseball Cap", price: 9.99 },
    { id: 16, type: "home", name: "LED Light Bulb", price: 6.0 },
    { id: 17, type: "music", name: "Vinyl Record", price: 24.99 },
    { id: 18, type: "medical", name: "Digital Thermometer", price: 11.5 },
    { id: 19, type: "food", name: "Box of Chocolates", price: 10.00 },
    { id: 20, type: "book", name: "Brave New World", price: 11.25 },
  ],
  apiUrl: "/api/cart",//TODO: set the right url
};
